"""Render a TailoredResume to HTML through the user's resume template.

The template is `~/.applypilot/resume_template.html` when present, otherwise the packaged
`config/resume_template.default.html`. Only the roles, bullets and skills come from the
TailoredResume. The header (name, contact line) comes from profile.json and education from
`~/.applypilot/resume_fixed.yaml`, so those blocks are identical on every tailored resume
and are never generated by the LLM.

`resume_fixed.yaml` format:

    education:
      - heading: "The Ohio State University, B.S. Data Analytics"
        dates: "May 2023"
        bullets: ["Specialization in ...", "Relevant coursework: ..."]
    header:                     # optional: name + contact line as on your resume (default: profile.json)
      name: "ALEX Q. TESTER"
      contact: [{text: "Springfield, IL"}, {text: "alex@example.com", href: "mailto:alex@example.com"}]
    roles:                      # optional: fixed title/company/dates/tagline per content-library role key
      data-science-associate-air:
        title: "Data Science Associate"
        company: "American Institutes for Research"
        dates: "Sep 2025 – present"
        tagline: "Non-profit organization ..."
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

import yaml
from jinja2 import Environment, StrictUndefined

from applypilot.config import (
    CONFIG_DIR,
    RESUME_FIXED_PATH,
    RESUME_PATH,
    RESUME_TEMPLATE_PATH,
    TEMPLATE_PREVIEW_PATH,
)
from applypilot.scoring.content_library import ContentLibrary, slugify
from applypilot.scoring.resume_model import Bullet, RoleEntry, TailoredResume

log = logging.getLogger(__name__)

DEFAULT_TEMPLATE_PATH = CONFIG_DIR / "resume_template.default.html"

_MONTH = r"(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\.?"
_DATE = rf"(?:{_MONTH}\s+)?\d{{4}}"
# A trailing date or date range at the end of a heading line, e.g. "Sep 2025 – present", "May 2023".
TRAILING_DATES = re.compile(
    rf"\s+({_DATE}(?:\s*[–—-]\s*(?:{_DATE}|[Pp]resent|[Cc]urrent))?)\s*$"
)


def split_trailing_dates(line: str) -> tuple[str, str]:
    """'The Ohio State University, B.S. ... May 2023' -> ('The Ohio State University, B.S. ...', 'May 2023')."""
    m = TRAILING_DATES.search(line)
    if not m:
        return line.strip(), ""
    return line[: m.start()].strip(), m.group(1).strip()


def education_from_resume_text(text: str) -> list[dict]:
    """Parse the EDUCATION section of a plain-text resume into fixed education entries.

    A line starting with a bullet marker continues the current entry; a line without one
    either starts an entry (when it ends with a date or there is no entry yet) or wraps
    onto the previous bullet.
    """
    entries: list[dict] = []
    for line in _section_lines(text, "EDUCATION"):
        if not line:
            continue
        if line[0] in "•-▪◦*":
            if entries:
                entries[-1]["bullets"].append(line[1:].strip())
            continue
        heading, dates = split_trailing_dates(line)
        if dates or not entries:
            entries.append({"heading": heading, "dates": dates, "bullets": []})
        elif entries[-1]["bullets"]:
            entries[-1]["bullets"][-1] += " " + line
        else:
            entries[-1]["heading"] += " " + line
    return entries


def _section_lines(text: str, name: str) -> list[str]:
    """Lines of an ALL-CAPS section of a plain-text resume, up to the next ALL-CAPS header."""
    lines = text.splitlines()
    try:
        start = next(i for i, ln in enumerate(lines) if ln.strip().upper() == name) + 1
    except StopIteration:
        return []
    out: list[str] = []
    for raw in lines[start:]:
        line = raw.strip()
        if line and line == line.upper() and len(line) > 3 and line[0].isalpha() and ":" not in line:
            break
        out.append(line)
    return out


def _match_role_key(title: str, library: ContentLibrary | None) -> str:
    """Content-library role key whose title (before the comma) equals this resume title."""
    if library:
        for role in library.roles:
            if role.title.split(",")[0].strip().lower() == title.strip().lower():
                return role.key
    return slugify(title)


def parse_base_resume(text: str, library: ContentLibrary | None = None) -> TailoredResume:
    """Parse WORK EXPERIENCE and SKILLS of the base resume (resume.txt) into a TailoredResume.

    Role lines look like 'Title at Company <dates>'; an unbulleted line right after one is the
    company tagline; '•' starts a bullet and other lines wrap onto the previous bullet. Bullets
    get empty project_ids. Role keys are matched to the content library by title when given.
    """
    roles: list[RoleEntry] = []
    for line in _section_lines(text, "WORK EXPERIENCE") or _section_lines(text, "EXPERIENCE"):
        if not line:
            continue
        if line[0] in "•-▪◦*":
            if roles:
                roles[-1].bullets.append(Bullet(text=line[1:].strip()))
            continue
        heading, dates = split_trailing_dates(line)
        if dates and " at " in heading:
            title, company = heading.split(" at ", 1)
            roles.append(RoleEntry(
                role_key=_match_role_key(title, library),
                title=title.strip(), company=company.strip(), dates=dates, tagline=None,
            ))
        elif roles and roles[-1].bullets:
            roles[-1].bullets[-1].text += " " + line
        elif roles:
            roles[-1].tagline = f"{roles[-1].tagline} {line}" if roles[-1].tagline else line

    skills: dict[str, str] = {}
    last = None
    for line in _section_lines(text, "SKILLS") or _section_lines(text, "TECHNICAL SKILLS"):
        if not line:
            continue
        cat, sep, items = line.partition(":")
        if sep and len(cat) <= 40 and "," not in cat:
            last = cat.strip()
            skills[last] = items.strip()
        elif last:
            skills[last] = f"{skills[last]} {line}".strip()
    return TailoredResume(roles=roles, skills=skills)


def fixed_roles_from_resume(resume: TailoredResume) -> dict[str, dict]:
    """role_key -> {title, company, dates, tagline}, the base resume's fixed facts per role."""
    return {
        r.role_key: {"title": r.title, "company": r.company, "dates": r.dates, "tagline": r.tagline}
        for r in resume.roles
    }


def load_fixed(path: Path | None = None, resume_text_path: Path | None = None) -> dict:
    """Load the fixed (never LLM-generated) resume blocks.

    Reads resume_fixed.yaml. Without one, education falls back to the EDUCATION section of
    resume.txt so users without a custom setup still get their education block.

    Returns:
        {"education": [{"heading", "dates", "bullets"}], "roles": {role_key: {...}}}
    """
    path = Path(path) if path else RESUME_FIXED_PATH
    data: dict = {}
    if path.exists():
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    education = data.get("education")
    if education is None:
        txt = Path(resume_text_path) if resume_text_path else RESUME_PATH
        education = education_from_resume_text(txt.read_text(encoding="utf-8")) if txt.exists() else []
    normalized = [
        {
            "heading": str(e.get("heading", "")).strip(),
            "dates": str(e.get("dates", "") or "").strip(),
            "bullets": [str(b).strip() for b in e.get("bullets") or []],
        }
        for e in education
        if isinstance(e, dict)
    ]
    header = data.get("header") or None
    if header:
        header = {
            "name": str(header.get("name", "")).strip(),
            "contact": [
                {"text": str(c.get("text", "")).strip(), "href": c.get("href") or None}
                for c in header.get("contact") or []
                if isinstance(c, dict)
            ],
        }
    return {"education": normalized, "roles": data.get("roles") or {}, "header": header}


def header_from_resume_text(text: str, profile: dict) -> dict | None:
    """Name and contact items from the first two lines of a plain-text resume.

    The contact line is split on '▫' or '|'. Email gets a mailto: link; 'LinkedIn' / 'GitHub'
    get the profile's URLs.
    """
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    if len(lines) < 2:
        return None
    p = profile.get("personal", {})
    contact = []
    for part in re.split(r"\s*[▫|]\s*", lines[1]):
        if not part:
            continue
        href = None
        if "@" in part:
            href = f"mailto:{part}"
        elif part.lower() == "linkedin":
            href = p.get("linkedin_url") or None
        elif part.lower() == "github":
            href = p.get("github_url") or None
        contact.append({"text": part, "href": href})
    return {"name": lines[0], "contact": contact}


def build_contact(profile: dict) -> list[dict]:
    """Contact items from profile.json, in the order of the user's resume header.

    Returns a list of {"text", "href"} (href may be None).
    """
    p = profile.get("personal", {})
    city = ", ".join(x for x in (p.get("city"), p.get("province_state")) if x)
    items: list[dict] = []
    if city:
        items.append({"text": city, "href": None})
    if p.get("email"):
        items.append({"text": p["email"], "href": f"mailto:{p['email']}"})
    if p.get("phone"):
        items.append({"text": p["phone"], "href": None})
    if p.get("linkedin_url"):
        items.append({"text": "LinkedIn", "href": p["linkedin_url"]})
    if p.get("github_url"):
        items.append({"text": "GitHub", "href": p["github_url"]})
    if p.get("portfolio_url"):
        items.append({"text": "Portfolio", "href": p["portfolio_url"]})
    return items


def _template_source(template_path: Path | None) -> str:
    if template_path is None:
        template_path = RESUME_TEMPLATE_PATH if RESUME_TEMPLATE_PATH.exists() else DEFAULT_TEMPLATE_PATH
    return Path(template_path).read_text(encoding="utf-8")


def render_resume(
    resume: TailoredResume,
    profile: dict,
    template_path: Path | None = None,
    fixed: dict | None = None,
) -> str:
    """Render a TailoredResume to a complete HTML document.

    Args:
        resume: The tailored content (roles, bullets, skills).
        profile: profile.json contents; supplies the name and contact line.
        template_path: Override the template; default is the user's template, then the packaged one.
        fixed: Pre-loaded fixed blocks (see load_fixed); loaded from disk when None.

    Returns:
        HTML string ready for pdf.render_pdf().
    """
    fixed = fixed if fixed is not None else load_fixed()
    header = fixed.get("header") or {}
    env = Environment(autoescape=True, undefined=StrictUndefined, trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_template_source(template_path))
    return template.render(
        name=header.get("name") or profile.get("personal", {}).get("full_name", ""),
        contact=header.get("contact") or build_contact(profile),
        roles=resume.roles,
        skills=list(resume.skills.items()),
        education=fixed["education"],
    )


def write_fixed_yaml(
    resume_text: str, library: ContentLibrary | None, profile: dict, path: Path | None = None
) -> Path:
    """Write resume_fixed.yaml from the base resume: header, education and per-role facts, verbatim."""
    path = Path(path) if path else RESUME_FIXED_PATH
    base = parse_base_resume(resume_text, library)
    data = {
        "header": header_from_resume_text(resume_text, profile),
        "education": education_from_resume_text(resume_text),
        "roles": fixed_roles_from_resume(base),
    }
    header = (
        "# Fixed resume blocks: copied into every tailored resume, never written by the LLM.\n"
        "# Generated from resume.txt by `applypilot template init`; edit freely.\n"
    )
    path.write_text(header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=1000), encoding="utf-8")
    return path


def preview_template(
    profile: dict,
    resume_text: str,
    library: ContentLibrary | None = None,
    out: Path | None = None,
    template_path: Path | None = None,
) -> dict:
    """Render the base resume's own content through the template to a PDF, for side-by-side review.

    Returns:
        render_pdf's dict plus "path" and "html_path" (the HTML is written next to the PDF).
    """
    from applypilot.scoring.pdf import render_pdf

    out = Path(out) if out else TEMPLATE_PREVIEW_PATH
    html = render_resume(parse_base_resume(resume_text, library), profile, template_path=template_path)
    html_path = out.with_suffix(".html")
    html_path.write_text(html, encoding="utf-8")
    return {"path": out, "html_path": html_path, **render_pdf(html, str(out))}


def resume_to_text(resume: TailoredResume, profile: dict, fixed: dict | None = None) -> str:
    """Plain-text export in the base resume's layout (for the apply agent, ATS text fields, the judge)."""
    fixed = fixed if fixed is not None else load_fixed()
    header = fixed.get("header") or {}
    name = header.get("name") or profile.get("personal", {}).get("full_name", "")
    contact = header.get("contact") or build_contact(profile)
    lines = [name, " ▫ ".join(c["text"] for c in contact), "", "WORK EXPERIENCE", ""]
    for role in resume.roles:
        head = f"{role.title} at {role.company}" if role.company else role.title
        lines.append(f"{head} {role.dates}".strip())
        if role.tagline:
            lines.append(role.tagline)
        lines.extend(f"• {b.text}" for b in role.bullets)
        lines.append("")
    lines += ["EDUCATION", ""]
    for e in fixed.get("education", []):
        lines.append(f"{e['heading']} {e['dates']}".strip())
        lines.extend(f"• {b}" for b in e["bullets"])
    lines += ["", "SKILLS", ""]
    lines.extend(f"{cat}: {items}" for cat, items in resume.skills.items())
    return "\n".join(lines).strip() + "\n"
