"""Render a TailoredResume to HTML through the user's resume template.

The template is `~/.applypilot/resume_template.html` when present, otherwise the packaged
`config/resume_template.default.html`. Only the roles, bullets and skills come from the
TailoredResume. The header (name, contact line) comes from profile.json and education from
`~/.applypilot/resume_fixed.yaml`, so those blocks are identical on every tailored resume
and are never generated by the LLM.

`resume_fixed.yaml` format:

    education:
      - heading: "The Ohio State University, B.S. Data Analytics"
        dates: "May 2023"
        bullets: ["Specialization in ...", "Relevant coursework: ..."]
    roles:                      # optional: fixed title/company/dates/tagline per content-library role key
      data-science-associate-air:
        title: "Data Science Associate"
        company: "American Institutes for Research"
        dates: "Sep 2025 – present"
        tagline: "Non-profit organization ..."
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

import yaml
from jinja2 import Environment, StrictUndefined

from applypilot.config import CONFIG_DIR, RESUME_FIXED_PATH, RESUME_PATH, RESUME_TEMPLATE_PATH
from applypilot.scoring.resume_model import TailoredResume

log = logging.getLogger(__name__)

DEFAULT_TEMPLATE_PATH = CONFIG_DIR / "resume_template.default.html"

_MONTH = r"(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\.?"
_DATE = rf"(?:{_MONTH}\s+)?\d{{4}}"
# A trailing date or date range at the end of a heading line, e.g. "Sep 2025 – present", "May 2023".
TRAILING_DATES = re.compile(
    rf"\s+({_DATE}(?:\s*[–—-]\s*(?:{_DATE}|[Pp]resent|[Cc]urrent))?)\s*$"
)


def split_trailing_dates(line: str) -> tuple[str, str]:
    """'The Ohio State University, B.S. ... May 2023' -> ('The Ohio State University, B.S. ...', 'May 2023')."""
    m = TRAILING_DATES.search(line)
    if not m:
        return line.strip(), ""
    return line[: m.start()].strip(), m.group(1).strip()


def education_from_resume_text(text: str) -> list[dict]:
    """Parse the EDUCATION section of a plain-text resume into fixed education entries.

    A line starting with a bullet marker continues the current entry; a line without one
    either starts an entry (when it ends with a date or there is no entry yet) or wraps
    onto the previous bullet.
    """
    lines = text.splitlines()
    try:
        start = next(i for i, ln in enumerate(lines) if ln.strip().upper() == "EDUCATION") + 1
    except StopIteration:
        return []

    entries: list[dict] = []
    for raw in lines[start:]:
        line = raw.strip()
        if not line:
            continue
        if line == line.upper() and len(line) > 3 and line[0].isalpha():
            break  # next ALL-CAPS section header
        if line[0] in "•-▪◦*":
            if entries:
                entries[-1]["bullets"].append(line[1:].strip())
            continue
        heading, dates = split_trailing_dates(line)
        if dates or not entries:
            entries.append({"heading": heading, "dates": dates, "bullets": []})
        elif entries[-1]["bullets"]:
            entries[-1]["bullets"][-1] += " " + line
        else:
            entries[-1]["heading"] += " " + line
    return entries


def load_fixed(path: Path | None = None, resume_text_path: Path | None = None) -> dict:
    """Load the fixed (never LLM-generated) resume blocks.

    Reads resume_fixed.yaml. Without one, education falls back to the EDUCATION section of
    resume.txt so users without a custom setup still get their education block.

    Returns:
        {"education": [{"heading", "dates", "bullets"}], "roles": {role_key: {...}}}
    """
    path = Path(path) if path else RESUME_FIXED_PATH
    data: dict = {}
    if path.exists():
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    education = data.get("education")
    if education is None:
        txt = Path(resume_text_path) if resume_text_path else RESUME_PATH
        education = education_from_resume_text(txt.read_text(encoding="utf-8")) if txt.exists() else []
    normalized = [
        {
            "heading": str(e.get("heading", "")).strip(),
            "dates": str(e.get("dates", "") or "").strip(),
            "bullets": [str(b).strip() for b in e.get("bullets") or []],
        }
        for e in education
        if isinstance(e, dict)
    ]
    return {"education": normalized, "roles": data.get("roles") or {}}


def build_contact(profile: dict) -> list[dict]:
    """Contact items from profile.json, in the order of the user's resume header.

    Returns a list of {"text", "href"} (href may be None).
    """
    p = profile.get("personal", {})
    city = ", ".join(x for x in (p.get("city"), p.get("province_state")) if x)
    items: list[dict] = []
    if city:
        items.append({"text": city, "href": None})
    if p.get("email"):
        items.append({"text": p["email"], "href": f"mailto:{p['email']}"})
    if p.get("phone"):
        items.append({"text": p["phone"], "href": None})
    if p.get("linkedin_url"):
        items.append({"text": "LinkedIn", "href": p["linkedin_url"]})
    if p.get("github_url"):
        items.append({"text": "GitHub", "href": p["github_url"]})
    if p.get("portfolio_url"):
        items.append({"text": "Portfolio", "href": p["portfolio_url"]})
    return items


def _template_source(template_path: Path | None) -> str:
    if template_path is None:
        template_path = RESUME_TEMPLATE_PATH if RESUME_TEMPLATE_PATH.exists() else DEFAULT_TEMPLATE_PATH
    return Path(template_path).read_text(encoding="utf-8")


def render_resume(
    resume: TailoredResume,
    profile: dict,
    template_path: Path | None = None,
    fixed: dict | None = None,
) -> str:
    """Render a TailoredResume to a complete HTML document.

    Args:
        resume: The tailored content (roles, bullets, skills).
        profile: profile.json contents; supplies the name and contact line.
        template_path: Override the template; default is the user's template, then the packaged one.
        fixed: Pre-loaded fixed blocks (see load_fixed); loaded from disk when None.

    Returns:
        HTML string ready for pdf.render_pdf().
    """
    fixed = fixed if fixed is not None else load_fixed()
    env = Environment(autoescape=True, undefined=StrictUndefined, trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_template_source(template_path))
    personal = profile.get("personal", {})
    return template.render(
        name=personal.get("full_name", ""),
        contact=build_contact(profile),
        roles=resume.roles,
        skills=list(resume.skills.items()),
        education=fixed["education"],
    )
